### ISSUE TITLE
Question about text_feature.pth

### ISSUE THREAD

**Issue by fengyao12** [ffhibnese/CGNC_Targeted_Adversarial_Attacks#2]
Good job! I have a question about text_feature.pth. Which version of the CLIP text encoder’s weights was used to generate this? Also, is this feature the final output from the text encoder?

**Comment by ffhibnese** [comment]
Thanks for your interest!
We use the default weights of the text encoder from the official repository of CLIP.
Yes, the provided text features are the output of CLIP's text encoder.

**Comment by cclucka** [comment]
Hello, I'm trying to reproduce the text_feature.pth so that I can test the model with classes other than "N8". However, when I usde the "default weights" and "a photo of a {class}", I don't obtain the same pth, and my evaluation results give me the class "rock python" whatever the target class. So I wanted to know what exactly are the default weights, and if you process the {class} in "a photo of a {class}" in some way (for example, are you feeding "sea_lion" or "sea lion" ?) Thank you in advance !

**Comment by krishnakanthnakkav2** [comment]
Hello Authors,

Is the clip model version is

```py
 "model, preprocess = clip.load('ViT-B/32', )
```

Can you please confirm.

**Comment by ffhibnese** [comment]
> Hello Authors,
> 
> Is the clip model version is
> 
> ```python
>  "model, preprocess = clip.load('ViT-B/32', )
> ```
> 
> Can you please confirm.

Hello! Thanks for your interest in our work.
The employed CLIP model is 'ViT-B/32'.
Help this message could solve your issue.
